name: Build Phoenix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.7.0
      - name: Build docs
        working-directory: docs
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Install ClangFormat
        run: brew install clang-format
      - name: Build Launcher
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: Phoenix.xcworkspace
          scheme: Launcher
          action: test build
      - name: Build Phoenix
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: Phoenix.xcworkspace
          scheme: Phoenix
          action: test build
